DWAPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.0 

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_trans: 0.2
  min_vel_trans: 0.1
  trans_stopped_vel: 0.1

  max_vel_theta: 1.0
  min_vel_theta: 0.4
  theta_stopped_vel: 0.4
  
  acc_lim_x: 0.5
  acc_lim_theta: 1.5
  acc_lim_y: 0.0

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1

  global_frame_id: odom